# Generated by Django 5.1.3 on 2024-12-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0005_product_views_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
