# Generated by Django 5.1.3 on 2024-12-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0006_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_time',
            field=models.CharField(default='3-4 days', max_length=50),
        ),
    ]
