# Generated by Django 5.1.3 on 2024-12-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0007_alter_product_shipping_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
    ]
